#ANTTUX grubcfg_maker.sh bash script
#2021, ANTi


#Generates a GNU's Not Unix GRand Unified Bootloader(lol) config file for ANTTUX
echo "Kernel name..."
read k_name
rm grub.cfg
touch grub.cfg
echo "#Generated by the grubcfg_maker.sh script, ANTi 2021!" >> grub.cfg
echo "timeout=0" >> grub.cfg
echo "menuentry "$k_name" {" >> grub.cfg
echo "	multiboot /boot/kernel" >> grub.cfg
echo "}" >> grub.cfg
echo "Done"

